### ISSUE TITLE
add more data to lcgms

### ISSUE THREAD

**Issue by mqli322** [NYCPlanning/cp-ceqr-schools#102]
- file:  W:\CEQR CommFacilities\1. Schools\2. Data\Helpful info
- file name: lcgms enroll in 2017 school year...
- info to be added: 
   - do not show in tool if charter (column D also shows include or exclude in tool)
   - use org level to determine whether school is relevant for PS, MS, or HS analysis
   - add grades served next to school name
   - pre-populate current enrollment using columns G-I
- Add as data source: https://data.cityofnewyork.us/Education/2013-2018-Demographic-Snapshot-School/s52a-8aq6

**Comment by mqli322** [comment]
- Note that the data referenced above is for latest enrollment information
- Add as data source for capacity information (end of Blue Book): https://dnnhh5cc1.blob.core.windows.net/portals/0/Capital_Plan/Utilization_Reports/Blue%20Book%202016-2017.pdf?sr=b&si=DNNFileManagerPolicy&sig=g7eZjXLOaaZfmXPHd0cFOjryIfBrVwF8D5mf9IFcSpA%3D

**Comment by pichot** [comment]
When you say "data source for capacity information" in the last comment above, do you mean point to this document as where they should find capacity numbers? If so, I think it should be indicated differently since it's not actually the source of the data they see on the screen.

**Comment by mqli322** [comment]
Yea former, just link as we usually do but there should be some note that info on capacity of schools opened in 2017-18 school year is at the end of the pdf. Otherwise folks will get confused why the B.B. is linked here

Mona (Qianmeng) Li
COMMUNITY FACILITIES PLANNER • CAPITAL PLANNING

NYC DEPT. OF CITY PLANNING
120 BROADWAY, 31st FLOOR • NEW YORK, NY 10271
212-720-3418 I qli@planning.nyc.gov
________________________________________
