### ISSUE TITLE
Add overarching intro and disclaimer language

### ISSUE THREAD

**Issue by mqli322** [NYCPlanning/cp-ceqr-schools#104]
You are viewing a prototype tool that can be used to assist city agencies, project sponsors, and the public in conducting certain quantitative analyses required by City Environmental Quality Review (CEQR).

The tool is built upon the 2014 CEQR Technical Manual guidelines and uses datasets developed in consultation between DCP and expert agencies. The conclusions displayed in the tool are preliminary, and may not reflect departures in analytical approach from Technical Manual guidelines where warranted.

**Comment by pichot** [comment]
Should this sit at the bottom/top of every page? Just on the index of project page?

**Comment by mqli322** [comment]
I was thinking the index page + the summary page
