### ISSUE TITLE
Language tweaks to Add New Project section

### ISSUE THREAD

**Issue by mqli322** [NYCPlanning/cp-ceqr-schools#105]
- [x] Question for John Mangin - should build year be analysis year?
- [x] Add link to ZoLa somewhere near the BBL field
- [x] Total Units - change sub-text to: “# of incremental units generated by project”
- [x] Senior Units - add sub-text: “Exclude units exclusively for seniors or HPD supportive housing facilities for special needs populations”

**Comment by pichot** [comment]
Do we have a response from John on 'build year' vs 'analysis year' ?

**Comment by mqli322** [comment]
I just added another comment to stick to build year
