### ISSUE TITLE
Existing conditions - More map labels

### ISSUE THREAD

**Issue by mqli322** [NYCPlanning/cp-ceqr-schools#62]
Legend should also include:
- [x] Project area (red boxes)
- [x] Study area (yellow subdistricts)
- [ ] New school opened (should this be marked with a slightly different symbol such as a green star? I'm using green stars to mark new schools under construction in other maps)
- [ ] High School not needed in the PS & IS maps since should be a separate, borough-wide map

- [x] Header should say: "Public schools serving the study area"

- [x] When school zones are turned on, should show "dbn", if the dbn column is blank - show "remarks"

**Comment by pichot** [comment]
Closing, two items moved to other issues
