### ISSUE TITLE
No action - schools under construction

### ISSUE THREAD

**Issue by mqli322** [NYCPlanning/cp-ceqr-schools#66]
Per discussion with SCA on methodology changes:
- Add column "Funding needed to complete" (Needed to Complete/Total Est Cost)
- Show guidance text: "Include capacity of new school if school is estimated to be complete in the school year prior to the project's build year AND funding needed to complete project is 20% or lower"

**Comment by pichot** [comment]
Use this dataset: https://nycplanning.carto.com/u/capitalplanning/dataset/capacity_projects_by_schools_add_org_level

**Comment by mqli322** [comment]
Consolidated list:

- [ ] Add column "Funding needed to complete" (Needed to Complete/Total Est Cost)
- [ ] Show guidance text: "Include capacity of new school if school is estimated to be complete in the school year prior to the project's build year AND funding needed to complete project is 20% or lower. Consult lead agency to confirm inclusion of new school(s)."
- [ ] Use this dataset: https://nycplanning.carto.com/u/capitalplanning/dataset/capacity_projects_by_schools_add_org_level
- [ ] Get rid of this data source: 
![image](https://user-images.githubusercontent.com/30453673/44290496-f8c6f900-a246-11e8-9393-4c3415eedf51.png)
