### ISSUE TITLE
Confirm borough-wide students from no-action housing projections

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/cp-ceqr-schools#84]

**Comment by mqli322** [comment]
W:\CEQR CommFacilities\1. Schools\2. Data\Helpful info

File name is Housing by SD 2016 - By Boro

**Comment by pichot** [comment]
This only has 2016 enrollment, is there data that has enrollment projections all the way to 2025, like PS and IS?

**Comment by mqli322** [comment]
It's just 1 number bc it's housing pipeline
________________________________

**Comment by pichot** [comment]
So one enrollment projection for any year in the future?

**Comment by mqli322** [comment]
The housing pipeline gets you students introduced by new housing, which is agnostic of year for PS and MS as well.

The enrollment projections are year by year. There is a separate HS file on the W drive for enrollment projections

________________________________
