### ISSUE TITLE
Existing conditions - flag to user if project located in choice district

### ISSUE THREAD

**Issue by mqli322** [NYCPlanning/cp-ceqr-schools#89]
Flag if project is located in a school zone (elementary or middle) that has school choice

**Comment by pichot** [comment]
Where is this defined? Like, is there a shapefile of school choice districts?

**Comment by mqli322** [comment]
It should be in the school zone shapefiles you’re already using. The DBN column will be blank and Remarks column will say sth that includes “choice”

**Comment by pichot** [comment]
Depends on #98
